let allStudents = [
  {
    id: 0,
    firstName: "Adan",
    lastName: "Hajyahya",
    capsule: 3,
    age: 32,
    city: "Taybe",
    gender: "Male",
    hobby: "Cooking",
  },
  {
    id: 1,
    firstName: "Adi",
    lastName: "Levy",
    capsule: 2,
    age: 27,
    city: "Holon",
    gender: "Male",
    hobby: "Economics",
  },
  {
    id: 2,
    firstName: "Ariel",
    lastName: "Moise",
    capsule: 5,
    age: 24,
    city: "Shoham",
    gender: "Female",
    hobby: "Playing the guitar",
  },
  {
    id: 3,
    firstName: "Aviran",
    lastName: "Pingle",
    capsule: 3,
    age: 29,
    city: "Tirat Ha Carmel",
    gender: "Male",
    hobby: "Basketball",
  },
  {
    id: 4,
    firstName: "Barak",
    lastName: "Damti",
    capsule: 1,
    age: 35,
    city: "Mitzpe Netufa",
    gender: "Male",
    hobby: "Reading",
  },
  {
    id: 5,
    firstName: "Benaya",
    lastName: "Trabelsi",
    capsule: 7,
    age: 34,
    city: "Harish",
    gender: "Male",
    hobby: "Mountain biking",
  },
];
